# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6e20d3e13d593d40694d8f77ff231f8cbbd585d9a09753a6c93f2b2dcaf6f5c267b57d8eed5526b562753f38b4ca8bbbb1c98adbf892c2aab13a2fb98e13bd9

test:
  secret_key_base: 8e554c5567900d90349ed5f4ccd42aeec8dcdb9677719d1e54d085cfe1d256df6b60da0300abb1b0dbb9b1a8d9f349967877b30ec35626b9824d818ab889dd97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
